### PR TITLE
add impressum

### PR DESCRIPTION
**Pull request by tuxmea**

### CODE REVIEW

**Comment by alvagante** [comment]
This is UGLY my friend. I'd add this info, the mininal required, in the footer of the page (where some of the same info is already present)

**Comment by tuxmea** [comment]
Did you check whether the information you provided are sufficient in terms of German jurisdiction?
As far as I know one needs the name "Impressum" somewhere easily findable on the website.

**Comment by alvagante** [comment]
I've seen other sites like this, with the legal notices link at the bottom.
Really no need to have the full impressum on the home page.

On Mon, Sep 7, 2015 at 6:01 PM, Martin Alfke notifications@github.com
wrote:

> Did you check whether the information you provided are sufficient in terms
> of German jurisdiction?
> As far as I know one needs the name "Impressum" somewhere easily findable
> on the website.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/example42/example42.github.io/pull/7#issuecomment-138331878
> .

## 

book { 'Extending Puppet':
  author  => 'Alessandro Franceschi',
  reviews => 'http://amzn.to/1nenFti',
}

**Comment by tuxmea** [comment]
OK. I see that you moved the impresses to another page.
Looks better.
I recommend to rename “Legal information” to “Impressum and Legal information”

**Comment by alvagante** [comment]
ok for me

**Pull request merged**
